### ISSUE TITLE
CORS error when trying to redirect to spotify authentication route

### ISSUE THREAD

**Issue by weisp014** [PrimeAcademy/aquamarine-syllabus#10]
## When redirecting user to spotify authentication route gettting this error in the console:
<img width="344" alt="image" src="https://user-images.githubusercontent.com/118697862/233152997-6249234f-c7bd-499a-96ca-d72d622e25f6.png">

Remember...

1. Describe
2. Isolate
3. Fix

These bug reports are intended to help you focus on Describe and Isolate so that Fixing can happen quickly.

Ryan

Want to redirect to spotify for authentication

**What is actually happening?**
See error above

## What did you try? Who did you ask?

Tried researching the issue and installed cors and required cors into server.js

## When was the last time you took a break?

Just had lunch.

**Comment by emmastout01** [comment]
I can look into this

**Comment by MaterDev** [comment]
Dane suggested alternate approach
