### ISSUE TITLE
Performance/Rendering Issues

### ISSUE THREAD

**Issue by Thomas-Vargas** [PrimeAcademy/aquamarine-syllabus#13]
## Description

Remember...

1. Describe
2. Isolate
3. Fix

These bug reports are intended to help you focus on Describe and Isolate so that Fixing can happen quickly.

**Your Name**

thomas-vargas

**What do you want to happen?**
new expenses and categories to appear on page when they are created without having to refresh. 

**What is actually happening?**

it only happens on page refresh and something is causing performance issues.

## What did you try? Who did you ask?
I tried moving the dispatch to another area outside of the page and changing the variable in the useeffect dependency array but that caused other issues.

## What branch is your code on? Did you git push?
group_dashboard, no

**Comment by emmastout01** [comment]
I worked with Thomas on this. I pulled his code down and ran it on my machine and didn't notice any performance issues. Thomas is trying some machine-specific fixes (including the tried-and-true 'turn it off and turn it on again' method) to see if that speeds up chrome performance.
