### ISSUE TITLE
SUPER QUICK post request fail

### ISSUE THREAD

**Issue by James5251996** [PrimeAcademy/aquamarine-syllabus#14]
## Description

Remember...

1. Describe
my post request is failing in my saga and do not know why
3. Isolate
I know it is in my saga
5. Fix

These bug reports are intended to help you focus on Describe and Isolate so that Fixing can happen quickly.

Trent

**What do you want to happen?**
to work

**What is actually happening?**

I get a status code 500

## Screenshots / Code Snippets
![5A7A74AC-4EC9-492B-A746-CACF8AF31B47](https://user-images.githubusercontent.com/118381259/233203280-83342ea5-4181-4778-8e05-4ef2faed02e8.jpeg)

![5B281937-0664-479F-A422-7BD98A9EA042](https://user-images.githubusercontent.com/118381259/233203126-3a1c50a4-0698-4a41-810f-4d8f9122e853.jpeg)

## What did you try? Who did you ask?
I console logged to see what data is coming through and there is no undefined data

**Comment by MaterDev** [comment]
Please include more information using the template. Screenshots and file information at the very least.

**Comment by emmastout01** [comment]
@James5251996 What is the error you're receiving in the server? Look at your server logs. That will give us the key information :)
