### ISSUE TITLE
not able to get req.query from get request

### ISSUE THREAD

**Issue by weisp014** [PrimeAcademy/aquamarine-syllabus#16]
## After logging in with spotify the user is redirected back to a server endpoint /api/spotify/callback and I'm trying to get the code from the url but nothing is logging out for req.query

Remember...

1. Describe
2. Isolate
3. Fix

These bug reports are intended to help you focus on Describe and Isolate so that Fixing can happen quickly.

Ryan

Want to get the access code from url that is sent back from spotify

Right now it doesn't seem to be hitting my end route

## Screenshots / Code Snippets

no error code to show

## What did you try? Who did you ask?

I doublechecked to make sure the redirect uri is correct. I can see that the code I want is in the url.

**Comment by emmastout01** [comment]
👀

**Comment by emmastout01** [comment]
Fixed! Ryan's issue was that he was was trying to make a `GET` request by redirecting to `localhost:3000/api/spotify/callback`, but in order for the server to be aware of the request he needed to hit `localhost:5000/api/spotify/callback`.
