### ISSUE TITLE
Setting State on Load

### ISSUE THREAD

**Issue by James5251996** [PrimeAcademy/aquamarine-syllabus#17]
## Description

Remember...

1. Describe
- I want to be able on load set the state using the information from my reducer. that way i can use it to set the value and when I go to edit the info when i leave a field unchanged it still will store that value.
3. Isolate
5. Fix

These bug reports are intended to help you focus on Describe and Isolate so that Fixing can happen quickly.

Trent

**What do you want to happen?**

**What is actually happening?**
I can not use 'details.id' when setting state as an example

## Screenshots / Code Snippets

![03A77296-86C6-42F3-B6E8-7F9BF01D1956](https://user-images.githubusercontent.com/118381259/233465027-6b6d5d25-651b-42ea-932f-0381e48d610a.jpeg)
this is the code to make the on change work. but the default state value of newTitle has no value on load so this breaks.

![2139B77B-9468-4330-8419-D3D97ED24CDC_4_5005_c](https://user-images.githubusercontent.com/118381259/233465312-2bef0539-191e-4a33-99c9-2534f5a43a2a.jpeg)
details is the name of my store and i would like the picture to work for title and use that to work for the others.
## When was the last time you took a break?
not long ago

**Comment by MaterDev** [comment]
Taking a look
