### ISSUE TITLE
how to render one page or another

### ISSUE THREAD

**Issue by sam4class** [PrimeAcademy/aquamarine-syllabus#18]
## Description
Hello, i'm trying to render one page unless there's input in the database, then i want to render a different page.

Remember...

1. I would like a list of lakes until the lakes are clicked as favorite, then i just want the favs listed
2. not quite sure what that looks like . . .
3. Fix: see the page that's wanted

**Samantha**

sam4class

**What do you want to happen?**
 render one page unless there's input in the database, then i want to render a different page.

**What is actually happening?**
i tried a couple ternary functions but they don't work or . . .? i'm just not wrapping my head around the solution   . . .
Thanks!

**Comment by emmastout01** [comment]
👀
