### ISSUE TITLE
How to send body on a GET request, or alternative solution

### ISSUE THREAD

**Issue by FCLee12** [PrimeAcademy/aquamarine-syllabus#19]
## Description

1. Describe
I am trying to send user input values to the saga then to the server, but I can't get the input values from the saga to the server. I've tried to use params, but it doesn't seem to be working or I can't seem to get the syntax correct. The user inputs will be used as part of the search parameters of the axios GET to the API database.

2. Isolate
Through following console.logs through the code, I can see that the input values are being moved as desired, but they don't make it to the server. Therefore, I've narrowed it down to the saga and the router.

These bug reports are intended to help you focus on Describe and Isolate so that Fixing can happen quickly.

**Your Name**

Fue Lee
GitHub: FCLee12

**What do you want to happen?**
I want to take user inputs from a modal, send them to the saga, have the saga send them to the server, then have the server use those input values as search parameters in a GET request to the API database to pull a list of search results.

**What is actually happening?**

I can't get the user inputs from the saga to the server due to axios GET requests not allowing a body object to be sent.

## Screenshots / Code Snippets

```
// this is the saga that is not able to send the user input to the server
function* fetchSearchResults(action) {
    try {
        // axios GET to server to grab search results from API DB
            // action.payload is an object
        console.log('this is action.payload in searchResults saga', action.payload);
        const title = action.payload.title;
        const artist = action.payload.artist;
        // this GET goes to the server which will make the GET request to the API database
            // but I can't send the user input stored in action.payload over to the server to use
            // as search parameters
        const searchResults = yield axios.get(`/api/musix/search`);
        console.log('searchResults:', searchResults);

        // // Sends the search results to the reducer
        //     // to be stored in the REDUX Store, ready for referencing
        yield put({
            type: 'SET_SEARCH_RESULTS',
            payload: searchResults
        });
    } catch (error) {
      console.log('API Search GET request for songs failed', error);
    }
}
```
This is server-side code that corresponds to the saga GET request:
```
// Get the list of search results based on search parameters
    // Need to figure out a way to make the q_track and q_artist and their values dynamic
router.get('/search', (req, res) => {
    console.log(req.params);
    console.log('this is req.params.title', req.params.title);
    console.log('this is req.params.artist', req.params.artist);
    let url = `http://api.musixmatch.com/ws/1.1/track.search?`;

    // function to dynamically build the URL based on parameters given
    const urlSearchBuilder = (urlString) => {
        let finalUrl = [urlString]
        if(req.params.title != '' && req.params.artist != '') {
            finalUrl.push(urlString + `q_track=${req.params.title}` + `&q_artist=${req.params.artist}`)
        }
        if(req.params.title == '') {
            console.log('q_track not needed');
        } else {
            finalUrl.push(urlString + `q_track=${req.params.title}`);
        }
        if(req.params.artist == '') {
            console.log('q_artist not needed');
        } else {
            finalUrl.push(finalUrl[finalUrl.length-1] + `&q_artist=${req.params.artist}`);
        }
        // console.log(finalUrl[finalUrl.length-1] + `&apikey=${process.env.MUSIXMATCH_API_KEY}`);
        return finalUrl[finalUrl.length-1] + `&apikey=${process.env.MUSIXMATCH_API_KEY}`;
    }
    // urlSearchBuilder(url);
    // res.sendStatus(200);
    axios.get(urlSearchBuilder(url))
    .then((response) => {
        // console.log('this is the track list', response.data.message.body.track_list);
        // console.log('this is the song track_id', response.data.message.body.track_list[0].track.track_id);
        // console.log('this is the song track_name', response.data.message.body.track_list[0].track.track_name);
        // console.log('this is the song artist_name', response.data.message.body.track_list[0].track.artist_name);

        // Sends the array of search results
        res.send(response.data.message.body.track_list);
    }) .catch((error) => {
        console.log('Error getting song list', error);
        res.sendStatus(500);
    })
})
```

## What did you try? Who did you ask?
I've looked online at using alternative requests POST or PUT, but it seems to be bad practice to use those. Additionally, I've tried to use Params but I think I'm getting the syntax incorrect.

## What branch is your code on? Did you git push?

I'm on a working branch feat-add-song, and the last time I committed was a few mins ago.

## When was the last time you took a break?

It's probably been an hour or so

**Comment by kdszafranski** [comment]
From your client to your server you could use POST. That might be the simplest, then you have a `body` on that request. GET does not have a body.

**Comment by FCLee12** [comment]
Sounds good, I'll give it a try, thanks Kris!

**Comment by FCLee12** [comment]
Looks like that did the trick, problem solved.
