### ISSUE TITLE
get latest issue

### ISSUE THREAD

**Issue by searley96** [PrimeAcademy/aquamarine-syllabus#20]
## Description

Remember...

1. Describe
2. Isolate
3. Fix

These bug reports are intended to help you focus on Describe and Isolate so that Fixing can happen quickly.

Siv

**What do you want to happen?**
Grab the latest row from the database, display on results page

**What is actually happening?**
grabbing all rows in database

## What did you try? Who did you ask?
double checking routes, must be missing something

**Comment by emmastout01** [comment]
👀

**Comment by emmastout01** [comment]
Fixed! The issue was that the route path was pointing at a `games` router, which already had a `GET` route to get all games. We needed to add `'/latest'` to the `GET` route path to point toward the route that would get the latest game.
