### ISSUE TITLE
GET request help for "sent message" data

### ISSUE THREAD

**Issue by phraunc** [PrimeAcademy/aquamarine-syllabus#22]
## Description

Remember...

1. Describe
I created another Reducer for 'sent messages' so I can see messages who I sent to as well as messages I have received.  I cannot get the sent messages to show on my DOM and dont know why. 
3. Isolate
4. Fix

These bug reports are intended to help you focus on Describe and Isolate so that Fixing can happen quickly.

**Your Name**

Anthony

**What do you want to happen?**
I want to show the messages sent on the DOM so i can create a EDIT button.
**What is actually happening?**

Nothing is happening.  I created another get rout to show "who" is sending the message as well as another reducer to store that information in.  The only errors I was getting was"; error Error: When called with an action of type "SENT_MESSAGE", the slice reducer for key "sentMessage" returned undefined. To ignore an action, you must explicitly return the previous state. If you want this reducer to hold no value, you can return null instead of undefined.".  

## Screenshots / Code Snippets
```
//useSelector to pull messageItems from the messageItems store
  const messageItems = useSelector((store) => store.messageItems);

  //useSelector to pull sent messages for the sentMessage Store to display in the 'Sent Messages' piece on the DOM. 
  const sentMessage = useSelector((store)=> store.sentMessage)

  console.log("here are my message items", messageItems);

  // use selector to pull userID from information generated on login. NOT used for anything sensitive.
  //  Keeping in mind that this is the whole object of the user in the store.
  const userID = useSelector((store) => store.user);

  // on page load, run 'FETCH_MESSAGE' -> results in rendering of MESSAGE.
  useEffect(() => {
    dispatch({
      type: "FETCH_MESSAGE",
    });
  }, []);

  useEffect(()=> {
  
    dispatch({
      type:"SENT_MESSAGE",
      payload: sentMessage,
    });
  }, []);
```

## What did you try? Who did you ask?
I tried a couple approaches with making a variable to hold the 'new message' data and include it into my useEffect for 'SENT_MESSAGE' so it would function.  

## What branch is your code on? Did you git push?
MAIN

## When was the last time you took a break?
LUNCH....

**Comment by MaterDev** [comment]
Issue identified and resolved. Had multiple, unintended, listeners for SENT_MESSAGE action
