### ISSUE TITLE
Server Get Request issue

### ISSUE THREAD

**Issue by James5251996** [PrimeAcademy/aquamarine-syllabus#23]
## Description

Remember...

1. Describe
- I am trying to get my search bar to work and every time i type a letter in  the search bar I get a server error that says i am passing in a parameter but the required statement requires none. 
3. Isolate
- I have narrowed this down to be a router issue but not sure why.
5. Fix

These bug reports are intended to help you focus on Describe and Isolate so that Fixing can happen quickly.

Trent

**What do you want to happen?**
to have the get results to show what i am trying to search for.

**What is actually happening?**

## Screenshots / Code Snippets
![4FABEDED-D05E-4785-AAE4-E1195C36F7D2](https://user-images.githubusercontent.com/118381259/234092561-dc4400e9-d3d2-42fd-922a-fde06d10fd08.jpeg)
What it shows in my browser
![88023839-D50E-4C78-9D54-301E0710106E](https://user-images.githubusercontent.com/118381259/234092587-f6780dd5-506a-4699-8f72-0e189b7f7432.jpeg)
This is what shows in my console on  vscode

**Comment by kdszafranski** [comment]
The % may be messing with the $1 syntax. Try:

pool.query(sqlText, [`%${req.params.recipesearch}%`]

**Comment by James5251996** [comment]
how does the sql text change? just leave a $1 there i take it?

**Comment by James5251996** [comment]
That did fix it. Thank you!
