### ISSUE TITLE
Dispatch on button click appears to be skipping over the saga and pushing data straight to the reducer

### ISSUE THREAD

**Issue by FCLee12** [PrimeAcademy/aquamarine-syllabus#24]
## Description

Remember...

1. Describe
2. Isolate
3. Fix

These bug reports are intended to help you focus on Describe and Isolate so that Fixing can happen quickly.

**Your Name**
Fue Lee

**Link to Repo**
https://github.com/FCLee12/Guess-The-Missing-Lyrics

**What do you want to happen?**
I want the dispatch call on button click to send data to the associated saga, so it can be used to send a POST request to the server to make a GET request to the MusixMatch API then store that information in the reducer to be accessed in the Add New Song modal
**What is actually happening?**
When I click the search button, all console.logs fire as suspected until the actual dispatch (which should be going to the saga) but none of the console.logs in the saga fire, and I don't see any console.logs from the associated server/router either. When tracking the logs across pages, it seems almost like there's something making a direct call to the reducer, but based on global searches, there doesn't seem to be any other action.type calls that match what the reducer would be listening for.

## Screenshots / Code Snippets
This is where the initial button click happens which should dispatch a call to the saga
NOTE: I've swapped the call to "taco-cat" just to see if that somehow breaks the call but the reducer is still receiving the data from the button click's dispatch
<img width="842" alt="Screenshot 2023-04-24 at 2 14 03 PM" src="https://user-images.githubusercontent.com/116466932/234093729-f14f1266-b319-4cf1-aaa9-cdb021488e5e.png">

This is the associated saga, it should be listening for a FETCH_SEARCH_RESULTS call
<img width="1043" alt="Screenshot 2023-04-24 at 2 06 00 PM" src="https://user-images.githubusercontent.com/116466932/234092128-d003846c-a528-4065-acd0-c83b2a552ea6.png">

This is the associated reducer, it should be listening for a SET_SEARCH_RESULTS call
NOTE: these console.logs are running every time I click the button to dispatch the data to the saga, and the values of the data being displayed match the data sent by that dispatch on the search button click (an object with a title property, its value, and a artist property, and its value)
<img width="1034" alt="Screenshot 2023-04-24 at 2 07 15 PM" src="https://user-images.githubusercontent.com/116466932/234092717-ce5fec24-1672-44d5-97e8-e6463a0779c2.png">

## What did you try? Who did you ask?
I've tried global searches verifying that I didn't make any accidental calls that match the call the reducer is listening for, and I didn't find anything. I did the same for the call that the initial search button click dispatches, but I didn't find any of those either. I've tried commenting out the call from the saga to the reducer, and the reducer was still receiving the value from the initial dispatch call from the search button click.

## What branch is your code on? Did you git push?
I am currently working on my feat-add-song branch, I haven't pushed it yet because it's not functional yet

## When was the last time you took a break?
I took a couple short breaks in the past hour

**Comment by kdszafranski** [comment]
The dispatched action type is "taco-cat".... should it be "FETCH_SEARCH_RESULTS"

**Comment by MaterDev** [comment]
Was unable to replicate issue. Appears to be working.
