### ISSUE TITLE
Search Bar Being one letter behind.

### ISSUE THREAD

**Issue by James5251996** [PrimeAcademy/aquamarine-syllabus#25]
## Description

Remember...

1. Describe
My search bar is sending requests based on the letter before the last one i typed. So the query is not reflecting what i have typed
3. Isolate
4. Fix

These bug reports are intended to help you focus on Describe and Isolate so that Fixing can happen quickly.

Trent

**What do you want to happen?**
i want the search bar and the results to match

**What is actually happening?**

## Screenshots / Code Snippets
![A10DAB88-24EA-4216-B261-4C73C95C7DFD](https://user-images.githubusercontent.com/118381259/234098785-344646cf-cbac-48b3-9ba7-57ff4cee3986.jpeg)
This is what i typed 'br'

![F3A6A450-6DD5-4921-8F38-D0E8407F67C9](https://user-images.githubusercontent.com/118381259/234098855-e282e5bd-e7c1-4165-a423-fcaac5132efe.jpeg)
this is what shows up instead 'b'

f the problem, and/or copy-paste relevant code and error messages. HINT: You can drag-and-drop images into the github editor! -->

**Comment by James5251996** [comment]
I believe this is an async issue but i am not sure how to make it synchronous.

**Comment by MaterDev** [comment]
needed to send event.target.value directly to dispatch instead of storing in state, which was causing an async issue
