### ISSUE TITLE
Rendering stuff to the dom when not expected

### ISSUE THREAD

**Issue by James5251996** [PrimeAcademy/aquamarine-syllabus#27]
## Description

Remember...

1. Describe
- when i click my submit button it populates another <p> tag and adds data to the dom when not wanted
3. Isolate
4. I know where the issue is but not seeing why this happens
5. Fix

These bug reports are intended to help you focus on Describe and Isolate so that Fixing can happen quickly.

Trent

![479E60A1-1E36-465C-A257-DAEABD85BC5E](https://user-images.githubusercontent.com/118381259/234316714-62b07412-83cc-46c5-82d6-31e6baef94b0.jpeg)
Here it shows the same info twice when it should only be once. 
![3F57C5A6-EDE1-4176-9FD4-6A9D36250F42](https://user-images.githubusercontent.com/118381259/234316871-ad9e4ba5-7af1-43c1-b3e1-8b1159db24c6.jpeg)
Here is the related code.

**What do you want to happen?**
I want to only show the results once

**What is actually happening?**

**Comment by emmastout01** [comment]
Looking into this 👀

**Comment by James5251996** [comment]
To add more context. This issue is happening on my Add recipe component and more specifically in my ingredient and direction input components. The code should not be adding more text to the DOM.

**Comment by James5251996** [comment]
Solved Thank you Emma
