### ISSUE TITLE
Can't navigate to /register

### ISSUE THREAD

**Issue by cplson** [PrimeAcademy/aquamarine-syllabus#28]
On a branch that I still have to merge, everything I need to do on it is complete but I can't navigate to the register page anymore for some reason. Here is the error that pops up.

![image](https://user-images.githubusercontent.com/52940969/234316518-acb9a1e9-f35c-4eaa-86da-eebf281ecfc0.png)
not sure if that image is gonna work so heres the text for it:  Warning: Hash history cannot PUSH the same path; a new entry will not be added to the history stack
warning @ tiny-warning.esm.js:11

I'm trying to navigate from /home -> /register i've made sure /register is not what I'm on when I start. I've checked the code against my main branch and I cannot find the cause.

Here's the Route in App.js:
![image](https://user-images.githubusercontent.com/52940969/234318230-09e131c3-5de5-4364-82b2-a1ecbd011ee5.png)

**Comment by MaterDev** [comment]
Was mixing route and protectedroute
