### ISSUE TITLE
Can't see new url when edited

### ISSUE THREAD

**Issue by searley96** [PrimeAcademy/aquamarine-syllabus#29]
## Description

Remember...

1. Describe
2. Isolate
3. Fix

These bug reports are intended to help you focus on Describe and Isolate so that Fixing can happen quickly.

Siv

**What do you want to happen?**
Edit my image

**What is actually happening?**

I can submit an new image url, in the "Action" state I can see the new url is being picked up, but it's not appearing in the database or DOM. I'm missing something.

## Screenshots / Code Snippets

router.put("/edit/:id", (req, res) => {
  // Update this single student
  const idToUpdate = req.params.id;
  console.log("MY IMAGE", req.body.image_url)
  const sqlText = `UPDATE "user" SET "image_url" = $1 WHERE id = $2`;
  pool
    .query(sqlText, [req.body.image_url, idToUpdate])
    
    .then((result) => {
      res.sendStatus(200);
    })
    .catch((error) => {
      console.log(`Error making database query ${sqlText}`, error);
      res.sendStatus(500);
    });
});

function EditForm() {
  const dispatch = useDispatch();
  const history = useHistory();

  const [editURL, setEditURL] = useState('')

//   const editImage = useSelector((store) => store.editReducer);

  const user = useSelector((store => store.user))

   //gets image from user table
   useEffect(() => {
    dispatch({ type: 'FETCH_IMAGE' });
  }, []);

const editItem = (incomingURL) => {
    // first check the URL input; if blank, change the URL to the existing one
    if (editURL === '') {
        setEditURL(incomingURL)
      }
      dispatch({
        type: 'EDIT_ITEM',
        payload: {
          image_url: editURL,
        }
      })
}

  return (
    <>
      <h1>Edit Image</h1>
      <h1 id='user-header'>Welcome, {user.username}!</h1>
      <img src={user.image_url} />
      
      <form onSubmit={() => editItem(user.id, user.image_url)} id= {user.id}>
      <input placeholder="new image url" value={editURL} onChange={(event) => setEditURL(event.target.value)} />
      <button type="submit" >Submit Edit</button>
      </form>
    </>
  );
}

function* editImage(action) {
    try {
      console.log("action.payload", action.payload);
      yield axios.put(`/api/user/${action.payload.id}`, action.payload);
      yield put({ type: "FETCH_USER" });
    } catch (error) {
      console.log("error editing image", error);
    }
  }
  
  function* editImageSaga() {
    yield takeLatest("EDIT_IMAGE", editImage);
  }

## What did you try? Who did you ask?
Tried googling issue. 

Looked in console, tried doing console.logs

**Comment by emmastout01** [comment]
I can help! :)

**Comment by emmastout01** [comment]
@searley96 You are super close! Take a look at the route path that you're using on your server, and the route path that you're using in your `axios.put` request. Do they match?

**Comment by emmastout01** [comment]
We worked together on this and edit functionality is working, hooray!
