### ISSUE TITLE
Bottom navigation bar is overlapping content on page

### ISSUE THREAD

**Issue by weisp014** [PrimeAcademy/aquamarine-syllabus#3]
## Bottom navigation bar is overlapping content on page

Remember...

1. Describe
2. Isolate
3. Fix

These bug reports are intended to help you focus on Describe and Isolate so that Fixing can happen quickly.

Ryan

I want the nav bar to be below the root content

**What is actually happening?**
Nav bar is covering content at bottom of page

## Screenshots / Code Snippets

<img width="347" alt="Screenshot 2023-04-17 at 3 47 22 PM" src="https://user-images.githubusercontent.com/118697862/232607224-893402ab-f28d-4af2-8df5-46733a8992bd.png">

## What did you try? Who did you ask?
I tried adding a box and paper around the nav bar after speaking with Key. Also searched issues with navigation bar covering page content.

## What branch is your code on? Did you git push?
Main
https://github.com/weisp014/solo-project

## When was the last time you took a break?
Recently

**Comment by MaterDev** [comment]
Looking into it

**Comment by MaterDev** [comment]
Resolved by surrounding routes with a box component, which has a bottom-padding:

<Box sx={{ pb: 9, backgroundColor: 'red' }}>
