### ISSUE TITLE
edit issues along with server issues.  

### ISSUE THREAD

**Issue by phraunc** [PrimeAcademy/aquamarine-syllabus#30]
## Description

Remember...

1. Describe
2. Isolate
3. Fix

These bug reports are intended to help you focus on Describe and Isolate so that Fixing can happen quickly.

**Your Name**

Anthony - Phraunc

**What do you want to happen?**
I want to render just 5 queries on the DOM and the edit to work when submit is hit, vice getting a server error 500
**What is actually happening?**

here is my information [] - in the server terminal - showing empty arrays
Server error 500, as well as client side issues

## Screenshots / Code Snippets

```
router.put("/:id", rejectUnauthenticated, (req, res)=>{
  const sqlText = `UPDATE "message" SET "category" = $1, "message" = $2, "recipient_id" = $3 WHERE "id" = $4 AND "user_id" = $5`
  const sqlParams = [req.body.category, req.body.message, req.body.recipient_id, req.params.id, req.user.id]

  pool.query(sqlText, sqlParams)
  console.log('sqlText, sqlParams', sqlText, sqlParams)
    .then((response)=>{res.sendStatus(200)})
    .catch((error)=>{res.sendStatus(500)})
})
```

## What did you try? Who did you ask?
I looked online for answers referring to  multiple DOM inputs, query questions and chatgbt

I used console logs to try and find the problem but I could not pin point the issue, just generally where it is.

## What branch is your code on? Did you git push?
MAIN

## When was the last time you took a break?
Just now.

**Comment by emmastout01** [comment]
Looking into this!
