### ISSUE TITLE
sign in issue

### ISSUE THREAD

**Issue by sam4class** [PrimeAcademy/aquamarine-syllabus#4]
## Am getting an error when trying to log in a user

Remember...

1. I hard coded two users, when I try to sign them in, I am getting an error
2. the error i'm getting, in the client side console, is telling me that the user is: (Unauthorized)
3. I tried to register the user again?  tho, of course that didn't work

**Samantha**

sam4class

**What do you want to happen?**
i would like to sign-in as a user that I hard coded in

**What is actually happening?**
the user is being denied access

POST http://localhost:3000/api/user/login 401 (Unauthorized)

Error with user login: Error: Request failed with status code 401
    at createError (createError.js:16:1)
    at settle (settle.js:17:1)
    at XMLHttpRequest.onloadend (xhr.js:54:1)

## What did you try? Who did you ask?

i went to my database and checked for errors there.  Also copied and pasted from there for an spelling errors
I did ask Lily.

**Comment by MaterDev** [comment]
Kris resolved

**Comment by kdszafranski** [comment]
the password will need to be "hashed" and not plain text like 1234. use the starting registration stuff to make users. Otherwise you could copy/paste a different project's (like the Shelf one) user password data into your project database.
