### ISSUE TITLE
(non-urgent) Conceptual issue on details page

### ISSUE THREAD

**Issue by dschilmoeller** [PrimeAcademy/aquamarine-syllabus#5]
## Description

I have a conceptual problem I'd like to work through. What I have are two lists of sprockets, one of which is the 'master' list of all available items, and the second of which would be items belonging to a specific user.
What I would like to do is go to an item details page when any of them are clicked (very similar to the movie list homework we did). 
The issue I'm trying to work through is the best way to render an item that belongs to a user when the user clicks on it from the master list page. 
I don't currently see a way around looping through the entire my_sprockets_table and then making some kind of decision - essentially, 
```
IF ( the sprocket.id clicked on in the master list page at any point === sprocket_id from the my_sprocket_table) { 
render the page as though the item belongs to me 
} else { 
render normal item details }. 
```
I'm guessing this is going to cause major lag in a deployed list. I'm wondering if I should have some kind of piece of state in place to deal with this. Would it make sense to, for example, create a piece of state generated from my_sprocket_table to check against locally, rather than trying to fetch the data and run through it each time [this of course presumes my_sprocket_table and this piece of state are updated when changes are made to said table as well, of course]. 

Or working through it, I might be able to do something even on the server side in, eg, the router to keep things relatively secure.

**Your Name**
Dschilmoeller
https://github.com/dschilmoeller/Prime-Solo-David-Schilmoeller

**What do you want to happen?**
Differing behavior when clicking a link through on an item depending on whether it appears on the user's list of owned items or not.

**What is actually happening?**

Not applicable, this is a conceptual type of question. 

## What branch is your code on? Did you git push?
Main at the moment. The code is up to date, including a fairly comprehensive SQL setup.

## When was the last time you took a break?
One is coming up soon!

**Comment by emmastout01** [comment]
I can help with this one!
