### ISSUE TITLE
Endless Looping Through a function when not wanted

### ISSUE THREAD

**Issue by James5251996** [PrimeAcademy/aquamarine-syllabus#6]
## Description

Remember...

1. Describe
- trying to capture data to prepopulate an input box with a value but it looks like it just endlessly runs the function
3. Isolate
- I believe it is how i am calling the function in the value property field 
5. Fix
- I am not sure on how to fix this
These bug reports are intended to help you focus on Describe and Isolate so that Fixing can happen quickly.

Trent Osterman

What i want is to display the text i get from my image into line items which should be possible.

**What is actually happening?**
The function seems to be continuously over and over

## Screenshots / Code Snippets
![2D582A80-AB45-4B12-B57E-566946BF1FB5](https://user-images.githubusercontent.com/118381259/232897187-296180f0-b863-46ea-8d6d-848bfefa9919.jpeg)

![CF11081C-B2F0-47BB-99B3-12A24C29A33E](https://user-images.githubusercontent.com/118381259/232897206-3b97808c-2696-4a8e-a7ef-a431d3b2400c.jpeg)

## What did you try? Who did you ask?

I tried different ways to call the function. 

I tried google. various ways to enter into the value field.

**Comment by MaterDev** [comment]
On it

**Comment by MaterDev** [comment]
Requested more information about the issue, such as code-snippets/file

**Comment by James5251996** [comment]
Added the pictures for more context.

**Comment by MaterDev** [comment]
The official documentation didnt have an example of tesseract being called as a function, so i created an example and shared with him so he could adapt it for his project.
