### ISSUE TITLE
time stamp troubles

### ISSUE THREAD

**Issue by phraunc** [PrimeAcademy/aquamarine-syllabus#7]
## Description

Remember...

1. Describe
3. Isolate
4. Fix

These bug reports are intended to help you focus on Describe and Isolate so that Fixing can happen quickly.

**Your Name**

phraunc

**What do you want to happen?**
I want to send a message using a POST request and get the timestamp when in the DOM.
**What is actually happening?**

the issue is is that I keep getting NULL for the timestamp when I get the payload back.  

## Screenshots / Code Snippets
```
THIS IS IN MY ROUTE:

router.post("/", rejectUnauthenticated, (req, res) => {
    const sqlText = `INSERT INTO "message" ("time_stamp","category","message","profile_id","recipient_id")
    VALUES($1, $2, $3, $4, $5)`;
    // 
    const sqlParams = [req.body.timestamp, req.body.category, req.body.message, req.body.recipient_id, req.user.id];

    pool
    .query(sqlText, sqlParams)
    .then((result) => {
        res.sendStatus(201)
    })
    .catch((err) => {
        console.log('error!', err)
        res.sendStatus(500)
    })
});

THIS IS IN MY MESSAGE COMPONENT:

const [newCategory, setNewCategory] = useState("");
  const [newMessage, inputNewMessage] = useState("");
//   const [newTimeStamp, inputNewTimeStamp] = useState('');
  const [newProfileId, inputNewProfileId] = useState('');
  const [newRecipientId, inputNewRecipientId]= useState('')

  const addNewMessage = (event) => {
    event.preventDefault()
    
    dispatch({
        type:'ADD_MESSAGE',
        payload:{
            time_stamp: Date.now(),
            category: newCategory,
            message: newMessage,
            profile_id: newProfileId,
            recipient_id: newRecipientId,
        }
        
    });
```

## What did you try? Who did you ask?
I tried googling a solution which there were plenty but the only thing I got out of it was use the Date.now() method.  I used chatgbt and they wanted me to change my params from req.body.timestamp to just timestamp but then I get an error message with it. 

## What branch is your code on? Did you git push?
main, yes

## When was the last time you took a break?
NEVER!!!!!!!!!!

**Comment by emmastout01** [comment]
Looking into this

**Comment by emmastout01** [comment]
We fixed this issue by having Tony store the timestamp as a default value in his database
