### ISSUE TITLE
POST problem

### ISSUE THREAD

**Issue by sam4class** [PrimeAcademy/aquamarine-syllabus#8]
## Post issues

Remember...

1. I am having problems getting my POST to the database
6. Fix: to be able to see my new POST in database

**Samantha**
github username:
sam4class

**What do you want to happen?**
i would love another set of eyes on my route

**What is actually happening?**

i am not getting an error 
I am also not getting my console.log on the server terminal
it's not getting to the server correctly

## What did you try? Who did you ask?

1. At first I couldn't find where the problem was
2. I went along and console.logged through the POST
3. it's going through the client side fine, it's just not hopping to the database
4. I checked the route in server, which looks right
5. i inserted with the right SQL text into the 'notes' table
6. i would love another set of eyes :)

## When was the last time you took a break?

yes, i do most likely need a break- but it's end of day!

**Comment by emmastout01** [comment]
I can look into this!

**Comment by emmastout01** [comment]
Fixed. The issue was that the saga to post data was not included in the `rootSaga`.
