### ISSUE TITLE
Get Trouble

### ISSUE THREAD

**Issue by searley96** [PrimeAcademy/aquamarine-syllabus#9]
## Description

Remember...

1. Describe
2. Isolate
3. Fix

These bug reports are intended to help you focus on Describe and Isolate so that Fixing can happen quickly.

Siv

**What do you want to happen?**
I want to get past games from my database and display them on the DOM on userPage

**What is actually happening?**
Getting error message map is not a function

When I console.log games, the variable that is accessing the store, I am not getting the data I want. I'm missing something.

## Screenshots / Code Snippets

![Screenshot 2023-04-19 at 10 30 08 AM](https://user-images.githubusercontent.com/119346063/233125500-6efd7e41-b98b-46e9-8fb4-f2deb1caaf4e.png)
![Screenshot 2023-04-19 at 10 30 43 AM](https://user-images.githubusercontent.com/119346063/233125650-9c69d46a-d89e-4095-9280-64ba98965b1c.png)
![Screenshot 2023-04-19 at 10 31 02 AM](https://user-images.githubusercontent.com/119346063/233125726-cc7868bd-3652-4933-b423-7126663c06ce.png)
![Screenshot 2023-04-19 at 10 31 16 AM](https://user-images.githubusercontent.com/119346063/233125801-20f786f7-e866-41da-b525-9e4420df38d6.png)

## What did you try? Who did you ask?
I tried adding conditional rendering, console.logging to see what data I'm actually getting, looked over all my code and routes but I'm not sure what I'm missing.

Console.log -->
 const games = useSelector((store) => store.gamesReducer);
 console.log('saved games', games)

**Comment by emmastout01** [comment]
Looking into it!

**Comment by emmastout01** [comment]
Fixed! Ryan pointed out that Siv needed to set up her games router in `server.js`.
